#define YAP_ROOTDIR       "/home/miguel/Desktop/yap-ns/arch"
#define YAP_BINDIR	    "/home/miguel/Desktop/yap-ns/arch/bin"
#define YAP_LIBDIR	    "/home/miguel/Desktop/yap-ns/arch/lib/Yap"
#define YAP_SHAREDIR	    "/home/miguel/Desktop/yap-ns/arch/share"
#define YAP_PL_SRCDIR	    "/home/miguel/Desktop/yap-ns/arch/share/Yap/pl"
#define YAP_STARTUP   "startup.yss"
#define YAP_SVERSION   "6.0.4"
#define YAP_VERSION 60004
#define MYDDAS_VERSION	    "MYDDAS-0.9.1"
#define YAP_ARCH	    "i686-linux"
#define YAP_LIBS	    "-lreadline -lncurses -ltermcap -lstdc++ -lm  -ldl -lnsl"
#define YAP_YAPLIB	    "libYap.a"
#define YAP_CC	    "gcc"
#define YAP_CFLAGS	    "-DBP_FREE -O3 -fomit-frame-pointer -Wall -Wstrict-prototypes -Wmissing-prototypes -DCUT_C=1  -DCOROUTINING=1 -DRATIONAL_TREES=1 -DDEPTH_LIMIT=1 -DTABLING=1 -DHAVE_CONFIG_H -D_YAP_NOT_INSTALLED_=1 -I. -I../H -I../OPTYap -I../BEAM -I../MYDDAS"
#define YAP_LDFLAGS    "-rdynamic "
#define YAP_SHLIB_SUFFIX    ".so"
#define YAP_TIMESTAMP "1278082357"
